global
        chroot /var/lib/haproxy
        user haproxy
        group haproxy

defaults
        mode http
        timeout connect 5000
        timeout client 50000
        timeout server 50000

frontend www
        bind *:10800
# generated by consul-template
{{ range services }}
  {{ $service := . }}
        acl host_{{ $service.Name }} hdr(host) -i {{ $service.Name | replaceAll "_" "." }}
    {{ end }}
  {{ end }}
  {{ range .Tags }}
    {{ if . | regexMatch "server_alias=" }}
        acl host_{{ $service.Name }} hdr(host) -i {{ . | regexReplaceAll ".*=" "" }}
    {{ end }}
  {{ end }}

        use_backend {{ .Name }}_backend if host_{{ .Name }}
{{ end }}

{{ range services }}
backend {{ .Name }}_backend
  {{ if .Tags | contains "sticky_session" }}
      # sticky
  {{ end }}
  {{ range service .Name }}
        server {{ .ID }} {{ .Address }}:{{ .Port }}
  {{ end }}
{{ end }}
