# generated by consul-template
## defaults
global
  log stdout local0
  stats socket /var/run/haproxy.sock mode 660 level admin expose-fd listeners

defaults
  log global
  mode http
  timeout connect 5000
  timeout client 5000
  timeout server 5000

## frontend
frontend www
  bind *:80

## acl
{{ range $service := services }}{{ range $tag := .Tags }}
acl host_{{ $service.Name }}_{{ $tag }}  hdr_beg(host) -i {{ $tag }}.{{ $service.Name }}.service
use_backend backend_{{ $service.Name }}_{{ $tag }} if host_{{ $service.Name }}_{{ $tag }}
{{ end }}{{ end }}
default_backend no-match

## backends
{{ range $service := services }}{{ range $tag := .Tags }}
backend backend_{{ $service.Name }}_{{ $tag }}
{{ range service $service.Name }}{{ if .Tags | contains $tag }}
  server {{ .ID }}-{{ .Node }} {{ .Address }}:{{ .Port }}
{{ end }}{{ end }}{{ end }}{{ end }}

backend no-match
  http-request deny deny_status 400
