# generated by consul-template
## defaults
defaults
  mode http
  timeout connect 5000
  timeout client 5000
  timeout server 5000

## frontend
frontend www
  bind *:80

## acl
{{ range services }}
acl host_{{ .Name }} hdr_beg(host) -i {{.Name | replaceAll "_" "." }}.service
use_backend {{ .Name }}_backend if host_{{ .Name }}
{{ end }}
default_backend no-match

## backends
{{ range services }}
backend {{ .Name }}_backend
{{ range service .Name }}
  server {{ .ID }}-{{ .Node }} {{ .Address }}:{{ .Port }}
{{ end }}
{{ end }}

backend no-match
  http-request deny deny_status 400
